### ISSUE TITLE
Missing signatures compared to the public instance

### ISSUE THREAD

**Issue by simone-co** [kevoreilly/CAPEv2#1072]
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I did read the README!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts
- [x] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

I tried to analyze [this sample](https://capesandbox.com/analysis/297569) in a new private cape installation.
I expected it to show the same signatures.

![cape-correct](https://user-images.githubusercontent.com/70196933/184103700-ccd87f31-091c-4872-9476-af52b0d92977.jpg)

# Current Behavior

![screen-cape](https://user-images.githubusercontent.com/70196933/184101014-8c4ddd0b-cb34-4aa5-a5c3-79422579b611.jpg)

# Failure Information (for bugs)

I tried to reload the signatures several times through community.py with argument -waf but unfortunately it seems that they are not seen.
I tried to change the configuration, reinstall the os and cape several times, but the problem is not solved.

## Steps to Reproduce

Analyze one sample in new fresh installation.

## Context

I followed the installation and configuration instructions.
they seem to be seen also from the web side less signature in the status field than in the public version.

| Question         | Answer
|------------------|--------------------
| Git commit       |  commit ab30a65ef1aa71a068a811b1501c57abe90598ad
| OS version       |  Ubuntu 22.04.1 LTS

## Failure Logs

![cape-log](https://user-images.githubusercontent.com/70196933/184104521-a0fc33de-7626-4830-b3db-223d9da71ac7.jpg)

**Comment by doomedraven** [comment]
Hello, thats because the detonation is different, maybe is some VM problems that gives you different output or less output. or less time executed in vm

**Comment by simone-co** [comment]
Hi, thank you for your reply.
I am aware that different configurations of the vm can change the behavior but the signature for dynamic load is not triggered either and in the behavior are the api LdrGetProcedureAddress, LdrLoadDll.
By checking [the rule](https://github.com/kevoreilly/community/blob/master/modules/signatures/dynamic_function_loading.py)  the signature should be flagged.
As you can see in these two analyses on the public instance (of the same file, just check sha256) the signatures change. 
[OLD](https://capesandbox.com/analysis/297569/) and [NEW](https://capesandbox.com/analysis/297999/ )


I would like to contribute to the cape project by reporting any bugs I find and proposing new features.

Thank you for your attention.

**Comment by doomedraven** [comment]
@kevoreilly could it be related to the recent LdrLoadDll that we spoke in PM?

**Comment by kevoreilly** [comment]
Nah that was specific to SL loading ntdll copy and has monitor workaround.

As I said before signatures are secondary to the behavior log. The process tree is also derived from the behavior log. Look at how they differ for those two jobs!

![image](https://user-images.githubusercontent.com/22219888/184165418-64444a5d-b49d-4167-b450-e72b1a0062f0.png)

![image](https://user-images.githubusercontent.com/22219888/184165582-36ffc714-5b95-4322-b5ce-d25a8ebbe411.png)

So the question here is really about massively differing detonations from the same sample. My first guess would be that the first job (297569) has (internet/vpn) route 'Italy' where the latter (297999) has route 'None' so couldn't download further stages, but that's at a glance. My point being this isn't really about signatures.

**Comment by doomedraven** [comment]
good point

**Comment by simone-co** [comment]
@kevoreilly  [New analysis](https://capesandbox.com/analysis/298014/) with route on italy has the same behavior as the no route.

OLD
![cape-old](https://user-images.githubusercontent.com/70196933/184175339-0e772354-8ad4-4194-ade5-9789bfa10964.png)

NEW
![cape-new](https://user-images.githubusercontent.com/70196933/184175363-e04a0763-dbf0-404a-8971-f90d45c9a8dc.png)

if we compare the two behaviors with the signature in the old analysis we see that the api chain is about the same.

![cape](https://user-images.githubusercontent.com/70196933/184175441-ba5bc6b8-e46e-481c-8b1a-5be80f98ef66.png)


Checking in the behavior section the signature api dynamic_function_loading.py is present but the signature is not shown.
If the api are present shouldn't the signature also be shown?
isn't it more likely to be two problems one on the detonation and one on the signature?

**Comment by kevoreilly** [comment]
Yes you are right, the presence of the apis in the log should result in the signature firing.

Looks like a slew of signature errors upon reprocessing... So I take it back! There is indeed a signature problem.

**Comment by doomedraven** [comment]
I will  check it after gym

**Comment by kevoreilly** [comment]
Cheers doomed

**Comment by simone-co** [comment]
I recommend also verifying that there are no problems in detonation.
Checking some analysis, from two days ago, in them show problems with thread follow and some anti-sandbox techniques, some samples do not detonate correctly and do not show all behavior, I investigate the problem and open another issues when I find out more.

To propose new bypasses and signatures, can issues be used or is it better to open a discussion?

Thank you for your attention.

**Comment by kevoreilly** [comment]
Issues is fine - just create a new issue for each sample/family that has detonation problems and ideally share a sample. I spend a lot of my life trying to solve detonation problems but am always grateful to have the information.

**Comment by doomedraven** [comment]
Open issue as those requieres solution

**Comment by doomedraven** [comment]
@simone-co you was right, there was bug in recent update. it wasn't matching properly `on_complete`.do git pull and test it please. it works now if i reprocess samples

**Comment by doomedraven** [comment]
update community with `python3 utils/community.py -waf`

**Comment by simone-co** [comment]
@doomedraven 
Hi, trying in the public instance would seem to work fine.
I will try on a new cape installation shortly. 

Thanks.

**Comment by simone-co** [comment]
In my cape instance the signature problem remains, in the behaviour there are calls to apis but signature not firing.
And it also presents a crash related to extract_overlay_data. 
![cape-error](https://user-images.githubusercontent.com/70196933/184360647-49310087-673e-4b7c-a131-1f439c4dea72.png)

Note that in the public instance the sample detonates only with vpn italy, but not with route italy (no vpn).
I'm italian and server is in italy but it no detonate correctly.

The vm I configured is currently invisible to pafish (except for rdtsc vmexit, new pafish version is with sleep).
![pafish](https://user-images.githubusercontent.com/70196933/184360727-18cb5d29-3003-47af-8de4-4b4f84f6cd7c.png)

I am continuing to investigate the problem to provide more information.

Thank you.

**Comment by doomedraven** [comment]
pafish is dead, use al-khaser for antivm testing ;)

about signature that is strange

**Comment by doomedraven** [comment]
@TheMythologist does it sound to you the error of the key in `process_overlay_file`? i see there is `self.key`

**Comment by doomedraven** [comment]
@simone-co did you restart cape-processor/process.py after update? did you update community repo too?

**Comment by TheMythologist** [comment]
> @TheMythologist does it sound to you the error of the key in `process_overlay_file`? i see there is `self.key`

Yup I should have used `dict.get` instead (probably because extract_overlay us disabled in config file)

**Comment by simone-co** [comment]
> @simone-co did you restart cape-processor/process.py after update? did you update community repo too?

Yes, I restart all cape's services every time after update and I do the same with community.
I'll update cape soon.

**Comment by doomedraven** [comment]
hm now im not really sure what is wrong, i just tested resubmitting sample instead of reprocess it and it works here. maybe try to add some debug statements in that signature `on_complete`

**Comment by doomedraven** [comment]
any update here?

**Comment by merfin993** [comment]
@doomedraven 
Hi, I'm luca the colleague of simone.co.
I apologize for the delayed reply.

We tried to do some debugging and all signatures seem to be running correctly.
(the conditions are executed correctly and also on_complete)
But, unfortunately, the signature is not shown yet.
Simone and I are continuing to investigate the problem.

Thanks.

**Comment by doomedraven** [comment]
np, thanks, let us know if you spot what is wrong

**Comment by doomedraven** [comment]
you can use `process.py -r X -sig -sn <signame>` to debug uniq sig

**Comment by doomedraven** [comment]
now i found case where signature is matched but cape says it not matched, investigating

**Comment by doomedraven** [comment]
i just pushed fix for my case, please do git pull and try again

**Comment by merfin993** [comment]
@doomedraven
Hi, the problem is not solved and has also reappeared on the public instance.

we can see it with the analysis.
https://capesandbox.com/analysis/311663/

Let's see the overview.
![overview](https://user-images.githubusercontent.com/108698184/191257649-acda7b4d-b477-4c18-b7b8-5be134fbc3b6.PNG)

The signature for dynamic loading not firing.
(https://github.com/kevoreilly/community/blob/master/modules/signatures/dynamic_function_loading.py)

In behaviour log we see LdrGetProcedureAddress and LdrLoadDll .
![behaviour](https://user-images.githubusercontent.com/108698184/191257714-a39dfcc5-3075-47b8-bc6d-f88f55b57e8d.PNG)

We continue to investigate.

Luca.

**Comment by doomedraven** [comment]
![Screenshot 2022-09-20 at 14 36 08](https://user-images.githubusercontent.com/1856495/191259089-893cf43f-2f09-4b52-aaa0-25ce9882a056.png)
your job, cape not always on latest, depends how much work we have, just pulled all updates and reprocessed and i see it. I also just in case resubmitted it and see it to not reprocess https://capesandbox.com/analysis/311680/

**Comment by merfin993** [comment]
@doomedraven Yes, the problem now is also solved on our private server, I apologize for assuming that the public instance was updated, sorry.

Luca.

**Comment by doomedraven** [comment]
glad that is solved, so yes the bug that i found last week was somehow related, not sure how it was working before with that bug %). let me know if you find any other problem. closing this one
